// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.UI.Data;

#nullable disable

namespace Test.UI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20241007174159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.UI.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Test.UI.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Test.UI.Models.Oper_Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oper_Classes");
                });

            modelBuilder.Entity("Test.UI.Models.Turnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Account")
                        .HasColumnType("int");

                    b.Property<int?>("Class_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Group_ID")
                        .HasColumnType("int");

                    b.Property<double>("Start_Active")
                        .HasColumnType("float");

                    b.Property<double>("Start_Passive")
                        .HasColumnType("float");

                    b.Property<double>("Turn_Credit")
                        .HasColumnType("float");

                    b.Property<double>("Turn_Debit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Class_ID");

                    b.HasIndex("Group_ID");

                    b.ToTable("Turnover");
                });

            modelBuilder.Entity("Test.UI.Models.Turnover", b =>
                {
                    b.HasOne("Test.UI.Models.Oper_Class", "Oper_Class")
                        .WithMany()
                        .HasForeignKey("Class_ID");

                    b.HasOne("Test.UI.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("Group_ID");

                    b.Navigation("Group");

                    b.Navigation("Oper_Class");
                });
#pragma warning restore 612, 618
        }
    }
}
